"""Stage 4: convert Unity AnimationClip (.anim) to Godot Animation .tres resources.

Uses a targeted regex parser instead of YAML: libyaml is pathologically slow in
this environment (12s for a 2.6 MB clip). The .anim layout is rigid:

    m_RotationCurves:  entries "- curve:" with quaternion keys
                       {time, value: {x,y,z,w}}, path: "SlendrinaMom\\x2fBip01 Pelvis"
    m_PositionCurves:  entries with SCALAR keys {time, value: f}, attribute:
                       m_LocalPosition.x|y|z, unquoted path, classID: 4
    m_ScaleCurves:     same with m_LocalScale.x|y|z
    m_FloatCurves:     same, generic value tracks
    m_Events:          trailing {time, functionName} list

Rotation quats are emitted as-is (Godot rotation_3d keys are x,y,z,w per the
reference .tres generated by the engine). Position/scale per-axis curves are
merged into single vector3 tracks (union of key times, previous-key hold for
missing axes).
"""
import os, sys, json, glob, re
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from unitylib import UNITY_SRC, PROJ, guid_of_meta, ensure_dir, fmt_float, unescape_unity

DB = os.path.join(PROJ, "tools", "db.json")
DST = os.path.join(PROJ, "converted", "animations")

FLOAT_RE = r"[-+]?[0-9]*\.?[0-9]+(?:[eE][-+]?[0-9]+)?"


def _slice(content, start_marker, end_marker):
    i = content.find(start_marker)
    if i < 0:
        return ""
    i += len(start_marker)
    if end_marker is None:
        return content[i:]
    j = content.find(end_marker, i)
    return content[i:j] if j >= 0 else content[i:]


def _entries(section):
    """Split a curve section on its "- curve:" entry markers."""
    parts = re.split(r"\n  - curve:\n", section)
    return parts[1:]


def _rot_quats(entry):
    keys = []
    for m in re.finditer(
            r"time:\s*(%s)\s*\n\s*value:\s*\{x:\s*(%s),\s*y:\s*(%s),\s*z:\s*(%s),\s*w:\s*(%s)\}"
            % (FLOAT_RE, FLOAT_RE, FLOAT_RE, FLOAT_RE, FLOAT_RE), entry):
        keys.append({"time": float(m.group(1)),
                     "value": {"x": float(m.group(2)), "y": float(m.group(3)),
                               "z": float(m.group(4)), "w": float(m.group(5))}})
    return keys


def _scalar_keys(entry):
    keys = []
    for m in re.finditer(r"time:[ \t]*(%s)[ \t]*\n[ \t]*value:[ \t]*(%s)" % (FLOAT_RE, FLOAT_RE), entry):
        keys.append((float(m.group(1)), float(m.group(2))))
    return keys


def _parse_rot_curves(section):
    curves = []
    for ent in _entries(section):
        # quoted paths may wrap several lines; re.S lets the quoted span newlines
        pm = re.search(r'path:[ \t]*"((?:[^"\\]|\\.)*)"', ent, re.S)
        keys = _rot_quats(ent)
        if keys and pm:
            curves.append({"curve": {"m_Curve": keys}, "path": unescape_unity(pm.group(1))})
    return curves


def _parse_axis_curves(section):
    """Scalar per-axis curves grouped per (path, attribute) -> merged vector3 tracks."""
    per_path = {}
    for ent in _entries(section):
        # NB: use [ \t]* after colons - \s* would span newlines and grab
        # unrelated lines when path/attribute is empty or the value is absent
        pm = re.search(r"path:[ \t]*([^\n]+)$", ent, re.M)
        am = re.search(r"attribute:[ \t]*([^\n]+)$", ent, re.M)
        keys = _scalar_keys(ent)
        if not (pm and am and keys):
            continue
        path = pm.group(1).strip().strip('"')
        attr = am.group(1).strip().strip('"')
        axis = attr.split(".")[-1]  # x|y|z
        per_path.setdefault(path, {}).setdefault(axis, keys)
    curves = []
    for path, axes in per_path.items():
        times = sorted({t for axis in axes.values() for t, _ in axis})
        axis_vals = {}
        for axis, kf in axes.items():
            vals = []
            prev = 0.0
            ki = 0
            for t in times:
                while ki < len(kf) and kf[ki][0] <= t:
                    prev = kf[ki][1]
                    ki += 1
                vals.append(prev)
            axis_vals[axis] = vals
        keys = []
        for i, t in enumerate(times):
            keys.append({"time": t, "value": {
                "x": axis_vals.get("x", [0.0] * len(times))[i],
                "y": axis_vals.get("y", [0.0] * len(times))[i],
                "z": axis_vals.get("z", [0.0] * len(times))[i]}})
        curves.append({"curve": {"m_Curve": keys}, "path": path})
    return curves


def _parse_events(section):
    events = []
    for m in re.finditer(r"time:[ \t]*(%s)[ \t]*\n[ \t]*functionName:[ \t]*\"?([A-Za-z0-9_]+)\"?" % FLOAT_RE, section):
        events.append({"time": float(m.group(1)), "functionName": m.group(2)})
    return events


def parse_anim_fast(path):
    with open(path, "r", errors="ignore") as f:
        content = f.read().replace("\r\n", "\n")
    clip = {}
    nm = re.search(r'm_Name:\s*"([^"]*)"', content)
    clip["m_Name"] = nm.group(1) if nm else ""
    wm = re.search(r"m_WrapMode:\s*(\d+)", content)
    clip["m_WrapMode"] = int(wm.group(1)) if wm else 0
    sr = re.search(r"m_SampleRate:\s*(\d+)", content)
    clip["m_SampleRate"] = int(sr.group(1)) if sr else 30
    st = re.search(r"m_StopTime:\s*(%s)" % FLOAT_RE, content)
    if st:
        clip["m_StopTime"] = float(st.group(1))
    clip["m_RotationCurves"] = _parse_rot_curves(
        _slice(content, "m_RotationCurves:", "m_CompressedRotationCurves:"))
    clip["m_PositionCurves"] = _parse_axis_curves(
        _slice(content, "m_PositionCurves:", "m_ScaleCurves:"))
    clip["m_ScaleCurves"] = _parse_axis_curves(
        _slice(content, "m_ScaleCurves:", "m_FloatCurves:"))
    # m_FloatCurves entries: scalar keys with attribute (property) targets.
    # Entries with an EMPTY path animate the legacy Animation component itself
    # (classID 111 / 95) - not representable in Godot; those are dropped.
    float_curves = []
    for ent in _entries(_slice(content, "m_FloatCurves:", "m_PPtrCurves:")):
        pm = re.search(r"path:[ \t]*([^\n]+)$", ent, re.M)
        am = re.search(r"attribute:[ \t]*([^\n]+)$", ent, re.M)
        cm = re.search(r"classID:[ \t]*(\d+)", ent)
        keys = _scalar_keys(ent)
        if pm and am and keys:
            path = pm.group(1).strip().strip('"')
            if not path:
                continue
            cls = int(cm.group(1)) if cm else 0
            if cls in (111, 95, 4):  # Animation/Animator/Transform handled elsewhere
                continue
            float_curves.append({"path": path, "attribute": am.group(1).strip().strip('"'),
                                 "keys": [{"time": t, "value": v} for t, v in keys]})
    clip["m_FloatCurves"] = float_curves
    clip["m_Events"] = _parse_events(_slice(content, "m_Events:", None))
    return clip


def build_tres(name, clip):
    out = []
    rot_curves = clip.get("m_RotationCurves") or []
    pos_curves = clip.get("m_PositionCurves") or []
    scale_curves = clip.get("m_ScaleCurves") or []
    float_curves = clip.get("m_FloatCurves") or []
    events = clip.get("m_Events") or []

    max_time = 0.0
    tracks = []

    def collect(curves, kind):
        nonlocal max_time
        for entry in curves:
            mcurve = (entry.get("curve") or {}).get("m_Curve") or []
            path = entry.get("path") or ""
            if path.startswith("/"):
                path = path[1:]
            flat = []
            for k in mcurve:
                t = float(k.get("time", 0.0))
                v = k.get("value") or {}
                max_time = max(max_time, t)
                if kind == "rotation_3d":
                    flat += [t, 1.0, v.get("x", 0.0), v.get("y", 0.0), v.get("z", 0.0), v.get("w", 1.0)]
                else:
                    flat += [t, 1.0, v.get("x", 0.0), v.get("y", 0.0), v.get("z", 0.0)]
            if flat:
                tracks.append((kind, path, flat))

    collect(rot_curves, "rotation_3d")
    collect(pos_curves, "position_3d")
    collect(scale_curves, "scale_3d")
    for entry in float_curves:
        path = entry.get("path") or ""
        attr = entry.get("attribute") or ""
        keys = entry.get("keys") or []
        times = [float(k["time"]) for k in keys]
        vals = [k.get("value", 0.0) for k in keys]
        for t in times:
            max_time = max(max_time, t)
        if times:
            prop_path = f"{path}:{attr}" if (path and attr) else (attr or path)
            tracks.append(("value", prop_path, {"times": times, "values": vals}))

    stop = clip.get("m_StopTime")
    length = float(stop) if stop else max_time
    if length <= 0.0:
        length = max_time
    if length <= 0.0:
        length = 0.01
    out.append('[gd_resource type="Animation" format=3]')
    out.append("")
    out.append("[resource]")
    out.append(f"length = {fmt_float(length)}")
    out.append("loop_mode = 0")
    for i, (kind, path, data) in enumerate(tracks):
        out.append(f'tracks/{i}/type = "{kind}"')
        out.append(f"tracks/{i}/imported = false")
        out.append(f"tracks/{i}/enabled = true")
        out.append(f'tracks/{i}/path = NodePath("{path}")')
        out.append(f"tracks/{i}/interp = 1")
        out.append(f"tracks/{i}/loop_wrap = true")
        if kind == "value":
            times, values = data["times"], data["values"]
            out.append(f"tracks/{i}/keys = {{")
            out.append(f'"times": PackedFloat32Array({", ".join(fmt_float(t) for t in times)}),')
            out.append(f'"transitions": PackedFloat32Array({", ".join("1" for _ in times)}),')
            out.append('"update": 0,')
            out.append(f'"values": [{", ".join(fmt_float(v) for v in values)}]')
            out.append("}")
        else:
            out.append(f"tracks/{i}/keys = PackedFloat32Array({', '.join(fmt_float(x) for x in data)})")
    for i, ev in enumerate(events):
        ti = len(tracks) + i
        t = float(ev.get("time", 0.0))
        fn = ev.get("functionName")
        if not fn:
            continue
        out.append(f'tracks/{ti}/type = "method"')
        out.append(f"tracks/{ti}/imported = false")
        out.append(f"tracks/{ti}/enabled = true")
        out.append(f'tracks/{ti}/path = NodePath(".")')
        out.append(f"tracks/{ti}/interp = 1")
        out.append(f"tracks/{ti}/loop_wrap = true")
        out.append(f"tracks/{ti}/keys = {{")
        out.append(f'"times": PackedFloat32Array({fmt_float(t)}),')
        out.append(f'"transitions": PackedFloat32Array(1),')
        out.append('"update": 0,')
        out.append(f'"values": [{{ "method": "{fn}", "args": [] }}]')
        out.append("}")
        if t > length:
            length = t
    out[3] = f"length = {fmt_float(length)}"
    out.append(f"; source unity clip: {name}")
    return "\n".join(out) + "\n"


def main():
    ensure_dir(DST)
    anims = sorted(glob.glob(os.path.join(UNITY_SRC, "**", "*.anim"), recursive=True))
    print(f"anim clips found: {len(anims)}", flush=True)
    out = {}
    used_names = {}
    n = 0
    for fp in anims:
        rel = os.path.relpath(fp, UNITY_SRC)
        clip = parse_anim_fast(fp)
        name = clip.get("m_Name") or os.path.splitext(os.path.basename(fp))[0]
        base = re.sub(r"[^A-Za-z0-9_]+", "_", name).strip("_") or "clip"
        c = used_names.get(base, 0)
        used_names[base] = c + 1
        fname = base if c == 0 else f"{base}_{c}"
        tres = build_tres(name, clip)
        with open(os.path.join(DST, fname + ".tres"), "w") as f:
            f.write(tres)
        g = guid_of_meta(fp + ".meta")
        if g:
            out[g] = f"res://converted/animations/{fname}.tres"
        n += 1
        if n % 25 == 0:
            print(f"  ...{n} clips", flush=True)
    with open(os.path.join(PROJ, "tools", "animations.json"), "w") as f:
        json.dump(out, f, indent=0)
    print(f"converted {n} animation clips", flush=True)


if __name__ == "__main__":
    main()